### PR TITLE
JDownloader2 and simpler base image

### PR DESCRIPTION
**Pull request by quickstar**

### CODE REVIEW

**Comment by quickstar** [comment]
Hi @hotio 
Any reason why this PR is not making it's way to the master?

cheers

**Comment by hotio** [comment]
Mainly because I have no interest in adding jdownloader and certainly no interest in debian, I've used it before, it's either horribly outdated or no security updates and bleeding edge, all of that for a few megabytes. I think ubuntu is a nice middle ground... The comment '# idk why this is needed?' also doesn't instill a whole lot of confidence, in a lot of places you are changing the indentation for no good reason too. It's also not the intention to use the environment variables for every little config setting.

But mainly 1 and 2, the rest is a bit of nitpicking, I will however change the maintainer label, didn't know it was deprecated.

**Comment by quickstar** [comment]
> Mainly because I have no interest in adding jdownloader
I can totally understand, especially because there is no direct radarr/sonarr integration, regardless it's pretty handy to have JDownloader at your fingertips.

> no interest in debian, I've used it before, it's either horribly outdated or no security updates and bleeding edge
Fair enough, even though I had a pretty good experience so far. It's just a personal dislike of canonical

>  The comment '# idk why this is needed?' also doesn't instill a whole lot of confidence
Any suggestions why I hat to chown the /app dir again? I cannot explain why this was necessary, since the script 10-install-app does exactly this already.

> in a lot of places you are changing the indentation for no good reason too
True, I'll fix this

> It's also not the intention to use the environment variables for every little config setting.
For sure it's not but I couldn't figure out a better way to pass in authentication information. Any idea?

> There's also some spelling mistakes and you only support one version.
I would be surprised if not, I'm so bad at spelling! Please tell me where they are :)
Actually I think, you can only get the latest JDownloader2 version. There seems to be no support for unstable or dev branches.

> But mainly 1 and 2, the rest is a bit of nitpicking
I got to say that I'm no really experienced in writing bash scripts. I just implemented JD because I need it in my environment and I thought It would be nice to share the work.
Did you think about implementing a torrent client download client as well? Which one would you prefer? I was actually thinking about integrating https://www.utorrent.com into the image. Any thoughts about this?

cheers and tnx for the feedback

**Comment by hotio** [comment]
For a torrent client it would have to include vpn and binhex is a lot better at that.

**Pull request closed without merging**
